name: search_me_up
description: Simple Search Ranking to make it easy to write ranked search algorithms.
version: 0.1.1
homepage: https://github.com/VHCBlade/search_me_up

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tuple: ^2.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
