name: search_me_up
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/VHCBlade/search_me_up

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tuple: ^2.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
